#!/usr/bin/env python3

import os
import sys
import curses as c
import curses.ascii as ascii

from datetime import datetime

from pylib.log import log
from pylib.terminal import sanitize_key

class Application:
    mainScr = None
    progPath = None
    args = None

    def __init__(s, progPath, args):
        s.progPath = progPath
        s.args = args

    def __enter__(s):
        s.init_curses()
        return s

    def __exit__(s, type, value, traceback):
        s.deinit_curses()

    # TODO: Enable color sup
    def init_curses(s):
        s.mainScr = c.initscr()
        c.noecho()
        c.cbreak()
        c.raw()
        s.mainScr.keypad(True)

    def deinit_curses(s):
        c.nocbreak()
        s.mainScr.keypad(False)
        c.echo()
        c.endwin()

    def show_key(s, key):
        s.mainScr.addstr('{} '.format(key))

        for c in key:
            s.mainScr.addstr('0x{:x} '.format(ord(c)))
        s.mainScr.addstr('\n')

    def handle_keystroke(s, key):
        s.show_key(key)

        if key == "Ctrl+Q":
            sys.exit()  # Throws SystemExit exception

    def start(s):
        s.mainScr.clear()
        while True:
            key = s.mainScr.getkey()
            key = sanitize_key(key)
            s.handle_keystroke(key)


def main(progPath, args):
    os.environ['ESCDELAY'] = '25'
    with Application(progPath, args) as app:
        app.start()


log("START")
main(sys.argv[0], sys.argv[1:])
log("END")


# if __name__ == '__main__':
#     try:
#         log("START")
#         main(sys.argv[0], sys.argv[1:])
#     except Exception as e:
#         print("ERROR:", e, file=sys.stderr)
#     except SystemExit:
#         pass
#     except:
#         print("ERROR: Unknown error.", file=sys.stderr)
#     finally:
#         log("END")
